### ISSUE TITLE
"Refresh Civitai Helper's additional buttons" broken with the latest DEV build of A1111-WebUI

### ISSUE THREAD

**Issue by AugmentedRealityCat** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#216] opened 2023-07-17 03:39 UTC
This extension is not working properly anymore with the latest DEV build of A1111.

This button 🔁 is still there, but it does not seem to work at all. 

These icons do NOT appear anymore:

🖼: Modified "replace preview" text into this icon

🌐: Open this model's Civitai url in a new tab

💡: Add this model's trigger words to prompt

🏷: Use this model's preview image's prompt

---

version: [v1.4.1-232-g7d26c479](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/7d26c479eebec03c2abb28f7b5226791688a7cea)  •  python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [22c84a4a0a](https://google.com/search?q=22c84a4a0a55b75a48935bed3ff73909f66d1673a53e12ac6d2400286bfdab03)

**Comment by Crazysl0th42** [comment] 2023-07-17 20:09
Is it possible to downgrade from the dev branch without it still being broken? I tried removing the dev git pull with the regular and still broken. I assume it just merged. Lmk if you figure out how to fix too

**Comment by SenaKashiwazaki** [comment] 2023-07-17 20:22
It broke for me on both the dev and production builds. Seems to be something with the addittion of the ability to view meta data in the extra network tab.

**Comment by axilesoft** [comment] 2023-07-22 13:49
I fixed it myself, opened pull request, to see if some one still maintain this git
My fork:
https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/tree/main

**Comment by neavo** [comment] 2023-07-25 07:18
> I fixed it myself, opened pull request, to see if some one still maintain this git My fork: https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/tree/main

it works well, thx

**Comment by Crazysl0th42** [comment] 2023-07-25 16:50
> I fixed it myself, opened pull request, to see if some one still maintain this git My fork: https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/tree/main

It works, but there is a duplicate of two of the buttons for me. I'll take that over not having functionality

**Comment by heartbreakergaming** [comment] 2023-07-27 00:44
> I fixed it myself, opened pull request, to see if some one still maintain this git My fork: https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/tree/main

How do i install your version? i tried copying your link into the Install by Url but that didnt work do i need to do something else?

**Comment by astroleander** [comment] 2023-07-27 12:34
> > I fixed it myself, opened pull request, to see if some one still maintain this git My fork: https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/tree/main
> 
> How do i install your version? i tried copying your link into the Install by Url but that didnt work do i need to do something else?

@heartbreakergaming 
1. In `Install from URL`
2. fill in `https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper` <- no surffix

**Comment by aomaoyyw** [comment] 2023-07-28 19:42
> > I fixed it myself, opened pull request, to see if some one still maintain this git My fork: https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/tree/main
> 
> How do i install your version? i tried copying your link into the Install by Url but that didnt work do i need to do something else?

现在的情况是，我必须每次在打开webui之后，去civitai helper里点击一下总是显示按钮，然后才能在扩展模型的卡片上看到4个图标。当然，这个civitai helper是axilesoft修改过的，并且那4个图标虽然能看到，但是排列的比较混乱，我尝试能不能上传一张图片来表达。

The current situation is that every time I open the webui, I have to go to the civitai helper and click the always show button, and then I can see 4 icons on the card of the extended model. Of course, this civitai helper was modified by axilesoft, and although the 4 icons can be seen, the arrangement is rather chaotic. I try to upload a picture to express it.
![无标题](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/33321738/0d567307-6a79-470d-98a2-d8097a5e7355)

**Comment by axilesoft** [comment] 2023-07-29 00:35
> 我这里没问题，你用的是dev分支么？
> I have no problem here, are you using the dev branch?

**Comment by axilesoft** [comment] 2023-07-29 00:36
> > > I fixed it myself, opened pull request, to see if some one still maintain this git My fork: https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/tree/main
> > 
> > 
> > How do i install your version? i tried copying your link into the Install by Url but that didnt work do i need to do something else?
> 
> 现在的情况是，我必须每次在打开webui之后，去civitai helper里点击一下总是显示按钮，然后才能在扩展模型的卡片上看到4个图标。当然，这个civitai helper是axilesoft修改过的，并且那4个图标虽然能看到，但是排列的比较混乱，我尝试能不能上传一张图片来表达。
> 
> The current situation is that every time I open the webui, I have to go to the civitai helper and click the always show button, and then I can see 4 icons on the card of the extended model. Of course, this civitai helper was modified by axilesoft, and although the 4 icons can be seen, the arrangement is rather chaotic. I try to upload a picture to express it. ![无标题](https://user-images.githubusercontent.com/33321738/256918658-0d567307-6a79-470d-98a2-d8097a5e7355.jpg)

> I have no problem here, are you using the dev branch?
> 我这里没有问题，你使用的是 dev 分支吗？

**Comment by AugmentedRealityCat** [comment] 2023-07-29 04:10
I am using the DEV branch and I have a very similar problem as the one described by @aomaoyyw .

**Comment by butaixianran** [comment] 2023-09-28 02:47
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

**Closed by butaixianran** 2023-09-28 02:47 UTC
